### ISSUE TITLE
Shown as offline, even when online

### ISSUE THREAD

**Issue by 240glt** [EionRobb/purple-teams#32] opened 2022-12-05 11:19 UTC
I can get online, and both send and receive messages. But other people see me as offline all the time. Using Pidgin for Windows, v2.14.10 and libteams.dll from https://eion.robbmob.com/libteams.dll. Running Windows 10.

Thanks for all the work you have put into this project!

**Comment by EionRobb** [comment] 2022-12-05 19:39
In the account settings, under the 'Advanced' tab, is the "Set global status" setting enabled?

**Comment by 240glt** [comment] 2022-12-06 07:12
Yes, it is. However, the "Tenant:" is left empty.

**Comment by 7kilobytes** [comment] 2022-12-12 16:24
Hello everyone,

Unfortunately, I have the same issue. Except other users are seeing the "Offline" status of mine they are also offline for me as well. Howevere, the messages are sent/received without issues.

**Comment by rddoove** [comment] 2023-01-02 10:22
I have the same issue. I see al other users as offline

**Comment by parneye** [comment] 2023-01-10 01:30
@EionRobb I also have "set global status" enabled, but other users see me as offline.
i am running pidgin 2.14.12 on windows 10 with https://eion.robbmob.com/libteams.dll and https://eion.robbmob.com/libjson-glib-1.0.dll.. everything else works perfectly, even the user is typing a message "..." display.. when i am typing from pidgin.
there are two issues mentioned above:
1- my status is seen as offline by other people. (there does not appear to be a fix to this, except for a work around where you can login to another teams client, or the teams website app and set your status from there - which is a bit tricky to manage to keep on top of it.. i've put myself in a pidgin group at the top of the UI so I can keep an eye on my status and manage it from the website)
2- on first adding teams to pidgin and connecting, everyone appears offline. this is easy fixed by exiting pidgin, and then opening pidgin again.

**Comment by parneye** [comment] 2023-01-11 01:21
@EionRobb in addition to my post yesterday, I wonder if the issue may be related to the "teams_set_statusid" method in "teams_messages.c".  There's a skipped part of the method due to a "return" with a "//TODO whats this one?" comment.
maybe that requires to be called too? 

``````
...
return;	
//TODO whats this one?
//https://presence.teams.microsoft.com/v1/me/endpoints/
post = g_strdup_printf("{\"id\":\"%s\",\"activity\":\"%s\",\"deviceType\":\"Desktop\"}", sa->endpoint, status);
teams_post_or_get(sa, TEAMS_METHOD_PUT | TEAMS_METHOD_SSL, TEAMS_PRESENCE_HOST, "/v1/me/endpoints/", post, NULL, NULL, TRUE);
g_free(post);`

**Comment by RaymiiOrg** [comment] 2023-03-21 06:06
> @EionRobb in addition to my post yesterday, I wonder if the issue may be related to the "teams_set_statusid" method in "teams_messages.c". There's a skipped part of the method due to a "return" with a "//TODO whats this one?" comment. maybe that requires to be called too?
> 
> ```
> ...
> return;	
> //TODO whats this one?
> //https://presence.teams.microsoft.com/v1/me/endpoints/
> post = g_strdup_printf("{\"id\":\"%s\",\"activity\":\"%s\",\"deviceType\":\"Desktop\"}", sa->endpoint, status);
> teams_post_or_get(sa, TEAMS_METHOD_PUT | TEAMS_METHOD_SSL, TEAMS_PRESENCE_HOST, "/v1/me/endpoints/", post, NULL, NULL, TRUE);
> g_free(post);`
> ```

I'm running `Pidgin 2.14.12 (libpurple 2.14.12)` and commit 34c73b2bceddc257843fe8f5d13babb972090029 (latest master as of now). 

I've had the same problem, when using pidgin others saw me as offline. 

Commenting that return and thus executing the `teams_post_or_get->TEAMS_PRESENCE_HOST` has solved that issue. I've not tested status changes like away yet, but at least when logging in I'm shown as online and that stays for at least an hour.

**Comment by RaymiiOrg** [comment] 2023-03-25 20:36
I've submitted a pull request regarding this issue: https://github.com/EionRobb/purple-teams/pull/37

**Closed** 2023-03-26 20:10 UTC

**Comment by 7kilobytes** [comment] 2023-03-29 14:38
The issue is still reproducible for me ☹

**Comment by RaymiiOrg** [comment] 2023-03-30 17:28
> The issue is still reproducible for me ☹

Have you recompiled the library using the latest code? I'm not sure the linked Windows libraries are updated as well...

**Comment by 7kilobytes** [comment] 2023-03-31 08:47
> > The issue is still reproducible for me frowning_face
> 
> Have you recompiled the library using the latest code? I'm not sure the linked Windows libraries are updated as well...

Yes. I am using the latest commit on linux:

int@sophi ~ 0 1.49 $ yay -Qs teams
local/purple-teams-git r73.87fe3e3-1
    MS Teams Plugin for Pidgin
int@sophi ~ 0 1.37 $
